name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/osx_64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "19197257-e4b302f9-2f17-452a-a8de-54b3fa66406c" -e "19197257-0799bf29-3e4d-47dd-8b2f-921ed7256ac5"
